### ISSUE TITLE
No 'version' key in the manifest file 

### ISSUE THREAD

**Issue by entropie** [marcschumacher/dwd_pollen#5]
```

Θ grep dwd ~ha/home-assistant.log
2021-04-10 18:17:58 WARNING (MainThread) [homeassistant.loader] You are using a custom integration dwd_pollen which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-04-10 18:17:58 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'dwd_pollen'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'dwd_pollen'
  File "/config/custom_components/dwd_pollen/sensor.py", line 19, in <module>

```

**Comment by entropie** [comment]
I added a version key;

```

2021-04-10 18:23:27 WARNING (MainThread) [homeassistant.loader] You are using a custom integration dwd_pollen which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-04-10 18:23:27 ERROR (MainThread) [homeassistant.config] Platform error: sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 847, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 485, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 490, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/dwd_pollen/sensor.py", line 19, in <module>
    from homeassistant.components.rest.sensor import RestData
ImportError: cannot import name 'RestData' from 'homeassistant.components.rest.sensor' (/usr/src/homeassistant/homeassistant/components/rest/sensor.py)

```
